# Add github config change label to any change of files in docs folder, or subfolders
github-config-change:
  - .github/**/*

# Add documentation label to any change of files in docs folder, or subfolders
documentation:
  - ./*.md
  - ./**/*.md

# Add code change label to any change of files ending with py
python-change:
  - ./*.py
  - ./**/*.py
