# https://github.com/K-Phoen/semver-release-action
name: Release

on:
  pull_request:
    types: closed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release
        uses: K-Phoen/semver-release-action@v1.3.1
        with:
          release_branch: main
          release_strategy: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}